services:
  - type: web
    name: skinova-clinic
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn skinova_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: skinova-clinic
          property: host
    database:
      name: skinova-db
      plan: free

